### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by zen2** [mbaraa/eloi#8]
At each time I launched eloi with arguments I got a SIGSEGV error:

```
# eloi --download
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x80c0af]

goroutine 1 [running]:
github.com/mbaraa/eloi/cmd.runWithGivenArgs(0x947ec0?, {0x0, 0x0})
	/var/tmp/portage/app-portage/eloi-0.2.0/work/eloi-0.2.0/cmd/cmd.go:49 +0x2f
github.com/mbaraa/eloi/cmd.Start()
	/var/tmp/portage/app-portage/eloi-0.2.0/work/eloi-0.2.0/cmd/cmd.go:44 +0xa9
main.main()
	/var/tmp/portage/app-portage/eloi-0.2.0/work/eloi-0.2.0/main.go:8 +0xf
```
Here it should tell me "this flag needs an argument":
```
# eloi --search
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x80c0af]

goroutine 1 [running]:
github.com/mbaraa/eloi/cmd.runWithGivenArgs(0x947ec0?, {0x0, 0x0})
	/var/tmp/portage/app-portage/eloi-0.2.0/work/eloi-0.2.0/cmd/cmd.go:49 +0x2f
github.com/mbaraa/eloi/cmd.Start()
	/var/tmp/portage/app-portage/eloi-0.2.0/work/eloi-0.2.0/cmd/cmd.go:44 +0xa9
main.main()
	/var/tmp/portage/app-portage/eloi-0.2.0/work/eloi-0.2.0/main.go:8 +0xf

```

It do not crash only without any argument to print out help.
Same behaviour with different version: 0.2.0, 0.2.2, 0.3.0.

My system use `dev-lang/go-1.23.1 (CPU_FLAGS_X86="sse2")`

**Comment by mbaraa** [comment]
@zen2 thanks for your report, I'll take a look into it!

**Comment by mbaraa** [comment]
fixed here https://github.com/mbaraa/eloi/commit/262c8ca2482dd9b72e27c40573850ed3225f7fb8, let me know if anything like it occurs again :)

also bumped version to [v0.3.1](https://github.com/mbaraa/eloi/releases/tag/v0.3.1)
